### ISSUE TITLE
Environment variable API_FOOTBALL_DATA is not set.

### ISSUE THREAD

**Issue by SoccerCashUK** [MauroAndretta/AIFootballPreictions#2]
Hi i'm getting this error

Traceback (most recent call last):
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\acquire_next_matches.py", line 322, in <module>
    get_next_matches(HEADERS, BASE_URL)
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\acquire_next_matches.py", line 193, in get_next_matches
    current_matchday = data['matches'][0]['season']['currentMatchday']  # int
                       ~~~~^^^^^^^^^^^
KeyError: 'matches'

James

**Comment by MauroAndretta** [comment]
Hi James!

The error you're encountering is likely due to the `API_KEY` environment variable not being set up correctly:

`API_KEY = os.getenv("API_FOOTBALL_DATA")`

Without this variable, the script cannot properly invoke the [Football-Data.org API](https://www.football-data.org/) to acquire the next matches information.

### How to Solve the Problem:

1. **Register for an API Key:**
   - Go to the [Football-Data.org website](https://www.football-data.org/) and register to get your personal API key.

2. **Create a `~/.env` File:**
   - This file will be used by the `load_dotenv` library to set up the `API_FOOTBALL_DATA` environment variable.
   - To create the file:
     - Open your terminal and run the command: `vim ~/.env`
     - This will create a new `~/.env` file if it doesn't already exist.

3. **Insert the API Key:**
   - After running the `vim` command, press the `i` key (for "insert mode").
   - Write down the following line, replacing `your_personal_key` with your actual API key:
     - `API_FOOTBALL_DATA=your_personal_key`

4. **Save and Exit:**
   - Press the `Esc` key to exit insert mode.
   - Then, type `:wq!` and press `Enter` to save the changes and exit the editor.

5. **Verify the Variable:**
   - To check if the variable has been properly set, run the following command from the terminal:
     - `cat ~/.env`
   - You should see the `API_FOOTBALL_DATA` variable listed with your API key.

Let me know if this solves your issue! Apologies for not mentioning this procedure in the `README.md` file.

As soon as I can, I will update the `README.md` with the `acquire_next_matches.py` script.

**Comment by SoccerCashUK** [comment]
Hi I made the .env file can you check i upload it here.
[https://file.io/O72Sm67UKXbU](url)
Because i tried running python scripts/acquire_next_matches.py --get_teams_names_dir data/processed --next_matches_output_file data/next_matches.json and still get same error,

Traceback (most recent call last):
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\acquire_next_matches.py", line 322, in <module>
    get_next_matches(HEADERS, BASE_URL)
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\acquire_next_matches.py", line 193, in get_next_matches
    current_matchday = data['matches'][0]['season']['currentMatchday']  # int
KeyError: 'matches'

James

**Comment by MauroAndretta** [comment]
Okay perfect the .env file is correct!

It looks like there's an issue with one of the keys being extracted from the API response, specifically with 'matches'. This might indicate that the API didn't return the expected data format.

I'll investigate this on my end and get back to you as soon as possible with a solution.

Thank you!

**Comment by MauroAndretta** [comment]
James, everything is working fine on my end. Could you please:

Pull the latest version of the code.

Remove the quotation marks around the API_KEY in your .env file. Change it from:

API_FOOTBALL_DATA="your_key"
to
API_FOOTBALL_DATA=your_key

**Comment by SoccerCashUK** [comment]
Hi did all that still the same

James

**Comment by MauroAndretta** [comment]
Try to pull now please, I've made some updates to print the logs for the request. 

And if you can paste it here.

**Comment by SoccerCashUK** [comment]
Hi I will check when I get home

James

**Comment by SoccerCashUK** [comment]
Hi I'm going through each stage now I let you know if I get any errors

**Comment by SoccerCashUK** [comment]
Hi still the same

James

**Comment by MauroAndretta** [comment]
Hi James,

can you please send me the complete error's log together with the python script you are using? Thanks!

**Comment by MauroAndretta** [comment]
It seems the script is unable to correctly retrieve the `API_FOOTBALL_DATA` environment variable from your `~/.env` file. Probably because it does not exist!

Could you please run the command `cat ~/.env` and share the result with me?

**Comment by SoccerCashUK** [comment]
PS C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main> cat .env
API_FOOTBALL_DATA=f820c1f84df04d05bb11a7cd166a8764

**Comment by MauroAndretta** [comment]
I see the issue. You're using a .env file located in C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main, but my Python script is set to load the environment variables from a .env file in your root directory (~/.env).

You have two options to resolve this:

1. Modify the acquire_next_matches.py script:

Change line 30 from:
load_dotenv(dotenv_path=os.path.expanduser("~/.env"))
TO
load_dotenv(dotenv_path=os.path.expanduser(".env"))

This will make the script use the .env file in the current directory instead of the root.

2. Follow the procedure in [this comment](https://github.com/MauroAndretta/AIFootballPreictions/issues/2#issuecomment-2314598333) and ensure you place your .env file in the root directory (~/.env).

This should definitively solve your problem!

**Comment by SoccerCashUK** [comment]
Hi that worked perfect going to run all again and see how it goes

James

**Comment by MauroAndretta** [comment]
I'm glad to hear that, James!

If you find this project helpful, I would greatly appreciate it if you could give it a star. Your support means a lot to me!
